[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyfunc"
version = "0.0.1"
dependencies = [
    "aiofiles",
    "httpx",
    "plotly",
    "pandas"
]